### ISSUE TITLE
Coponent wrapped with s2i as a REST server tries to start a gRPC server.

### ISSUE THREAD

**Issue by becartef** [SeldonIO/seldon-java-wrapper#5]
It applies to version 0.1.3 AND 0.1.4.

Deploying the component with
`
kubectl apply -f <resource_def_file_name>.json -n <namespace>
`

causes the following error in the log:

`
2019-02-12 14:57:48.150  INFO 1 --- [           main] io.seldon.wrapper.grpc.SeldonGrpcServer  : grpc port 5001
2019-02-12 14:57:48.588  INFO 1 --- [           main] .s.a.AnnotationAsyncExecutionInterceptor : No TaskExecutor bean found for async processing
2019-02-12 14:57:48.619  INFO 1 --- [cTaskExecutor-1] io.seldon.wrapper.grpc.SeldonGrpcServer  : Starting grpc server
2019-02-12 14:57:49.121 ERROR 1 --- [cTaskExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void io.seldon.wrapper.grpc.SeldonGrpcServer.runServer() throws java.lang.InterruptedException,java.io.IOException'.

java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:160) ~[grpc-netty-1.0.0.jar!/:1.0.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:147) ~[grpc-core-1.0.0.jar!/:1.0.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:79) ~[grpc-core-1.0.0.jar!/:1.0.0]
	at io.seldon.wrapper.grpc.SeldonGrpcServer.start(SeldonGrpcServer.java:94) ~[seldon-core-wrapper-0.1.4.jar!/:0.1.4]
	at io.seldon.wrapper.grpc.SeldonGrpcServer.runServer(SeldonGrpcServer.java:86) ~[seldon-core-wrapper-0.1.4.jar!/:0.1.4]
	at io.seldon.wrapper.grpc.SeldonGrpcServer$$FastClassBySpringCGLIB$$d398e0a2.invoke(<generated>) ~[seldon-core-wrapper-0.1.4.jar!/:0.1.4]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) ~[spring-aop-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.BindException: Address in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_131]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_131]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:511) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:496) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451) ~[netty-common-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-common-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401) ~[netty-transport-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[netty-common-4.1.3.Final.jar!/:4.1.3.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[netty-common-4.1.3.Final.jar!/:4.1.3.Final]
	... 1 common frames omitted
`

**Comment by marrrcin** [comment]
I love how the reported bugs have absolutely no response in this community.

**Comment by ukclivecox** [comment]
The core repo is https://github.com/SeldonIO/seldon-core and several Java issues are discussed there, e.g. https://github.com/SeldonIO/seldon-core/issues/1796

The Java wrapper is currently an incubation project and we welcome contributors to make it more stable and eventually GA.
